<?php

declare(strict_types=1);

/** @var \Qoliber\NebulaPageBuilder\Block\MasterTemplate $block */
$elements = $block->getElements();
$main = $elements['main'] ?? [];
$data = $block->getNodeData();
$html = $data['html'] ?? '';
$mainStyle = $block->buildStyleString($main['styles'] ?? []);
$classes = implode(' ', $main['cssClasses'] ?? []);
?><div data-content-type="html" data-appearance="default"<?php if ($classes) :
    ?> class="<?= $escaper->escapeHtmlAttr($classes) ?>"<?php
endif; ?><?php if ($mainStyle) :
    ?> style="<?= $escaper->escapeHtmlAttr($mainStyle) ?>"<?php
endif; ?>><?= /* @noEscape */ $html ?></div>
