<?php

declare(strict_types=1);

/**
 * Snippet: store_website_link
 *
 * @var \Magento\Framework\View\Element\Template $block
 */

$value = $block->getData('value');
$item = $block->getData('item');
$websiteId = $item['website_id'] ?? '';

if ($value) {
    $url = $block->getUrl('adminhtml/system_store/editWebsite', ['website_id' => $websiteId]);
    ?>
    <a href="<?= $escaper->escapeUrl($url) ?>" class="text-nebula-600 hover:text-nebula-500 dark:text-nebula-200 dark:hover:text-nebula-100 font-medium">
        <?= $escaper->escapeHtml($value) ?>
    </a>
    <?php
}
