<?php

declare(strict_types=1);

/** @var \Magento\Backend\Block\Widget\Form\Container $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?= /* @noEscape */ $block->getFormInitScripts() ?>
<?= $block->getFormHtml() ?>
<?php
$scriptString = <<<script
require([
    'jquery',
    'mage/mage'
], function($) {
    $('#edit_form').mage('form').mage('validation', {
        validationUrl: '{$block->escapeJs($block->getValidationUrl())}',
        highlight: function(element) {
            var detailsElement = $(element).closest('details');
            if (detailsElement.length && detailsElement.is('.details')) {
                var summaryElement = detailsElement.find('summary');
                if (summaryElement.length && summaryElement.attr('aria-expanded') === "false") {
                    summaryElement.trigger('click');
                }
            }
            $(element).trigger('highlight.validate');
        }
    });
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?= /* @noEscape */ $block->getFormScripts() ?>
