<?php

declare(strict_types=1);

/** @var \Qoliber\NebulaPageBuilder\Block\MasterTemplate $block */
$elements = $block->getElements();
$main = $elements['main'] ?? [];
$mainStyle = $block->buildStyleString($main['styles'] ?? []);
$classes = implode(' ', $main['cssClasses'] ?? []);
$childrenHtml = $block->getChildrenHtml();
?><div data-content-type="buttons" data-appearance="stacked"<?php if ($classes) :
    ?> class="<?= $escaper->escapeHtmlAttr($classes) ?>"<?php
endif; ?><?php if ($mainStyle) :
    ?> style="<?= $escaper->escapeHtmlAttr($mainStyle) ?>"<?php
endif; ?>><?= /* @noEscape */ $childrenHtml ?></div>
